### ISSUE TITLE
Expected class kotlinx.serialization.json.JsonObject as the serialized body of kotlinx.serialization.Polymorphic<List>, but had class kotlinx.serialization.json.JsonArray

### ISSUE THREAD

**Issue by H-AbdulMateen** [SebastianAigner/my-bird-app#2]
App crashes with this warning. Can someone explain why it is happening and what is the solution?

**Comment by SebastianAigner** [comment]
Could you post the full stack trace?

**Comment by H-AbdulMateen** [comment]
```
FATAL EXCEPTION: main
                                                                                                    Process: com.myapplication.MyApplication, PID: 10347
                                                                                                    io.ktor.serialization.JsonConvertException: Illegal input: Expected class kotlinx.serialization.json.JsonObject as the serialized body of kotlinx.serialization.Polymorphic<List>, but had class kotlinx.serialization.json.JsonArray
                                                                                                    	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:90)
                                                                                                    	at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1$2.emit(Emitters.kt:224)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
                                                                                                    	at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1.collect(SafeCollector.common.kt:113)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ReduceKt.firstOrNull(Reduce.kt:243)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt.firstOrNull(Unknown Source:1)
                                                                                                    	at io.ktor.serialization.ContentConverterKt.deserialize(ContentConverter.kt:123)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation.convertResponse$ktor_client_content_negotiation(ContentNegotiation.kt:230)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invokeSuspend(ContentNegotiation.kt:262)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(Unknown Source:13)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(Unknown Source:6)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
                                                                                                    	at io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:177)
                                                                                                    	at io.ktor.client.HttpClient$4.invoke(Unknown Source:11)
                                                                                                    	at io.ktor.client.HttpClient$4.invoke(Unknown Source:6)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:142)
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(Unknown Source:13)
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(Unknown Source:6)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
                                                                                                    	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
                                                                                                    	at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:88)
                                                                                                    	at AppKt.getImages(App.kt:75)
                                                                                                    	at AppKt$getImages$1.invokeSuspend(Unknown Source:12)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@77cf593, androidx.compose.runtime.BroadcastFrameClock@5b989d0, StandaloneCoroutine{Cancelling}@edd3dc9, AndroidUiDispatcher@f7cbcce]
2023-07-31 20:28:28.981 10347-10347 AndroidRuntime          com.myapplication.MyApplication      E  Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Expected class kotlinx.serialization.json.JsonObject as the serialized body of kotlinx.serialization.Polymorphic<List>, but had class kotlinx.serialization.json.JsonArray
                                                                                                    	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
                                                                                                    	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:94)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:81)
                                                                                                    	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
                                                                                                    	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:82)
                                                                                                    	... 40 more
```
> Could you post the full stack trace?

**Comment by SebastianAigner** [comment]
@H-AbdulMateen Are you using the exact code from this repository? I would usually guess that this error means that something with content negotiation isn't set up correctly, but I can't reproduce it on my side.

```kotlin
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.client.request.get
import io.ktor.serialization.kotlinx.json.json
```

...and then setting up the client itself:
```kotlin
    private val httpClient = HttpClient {
        install(ContentNegotiation) {
            json()
        }
    }
```

Also, please make sure you specify the correct generic type when making the actual request:

```kotlin
val images = httpClient
            .get("https://sebastianaigner.github.io/demo-image-api/pictures.json")
            .body<List<BirdImage>>()
```

In case none of these work, it would be great if you could zip your current project state and upload it as a reproducer :)

**Comment by hodakl099** [comment]
Hi @SebastianAigner I have the same issue and I had the same stack trace as @H-AbdulMateen. here is the link of my repo https://github.com/hodakl099/KMM-DEMO.git

**Comment by SebastianAigner** [comment]
Thanks. That reproduces on my machine. Will investigate!

**Comment by SebastianAigner** [comment]
Found the problem: This is caused by some version incompatibilities.

- The project in this repo uses Kotlin 1.8.21, but the template has been updated in the meantime to use Kotlin 1.9.0.
- This means you also need to update the other dependencies:
    - In `plugins`, make sure you specify `kotlin("plugin.serialization") version "1.9.0"`.
    - In your `common` dependencies, make sure you update Ktor to the latest version:

```kotlin
implementation("io.ktor:ktor-client-core:2.3.2")
implementation("io.ktor:ktor-client-content-negotiation:2.3.2")
implementation("io.ktor:ktor-serialization-kotlinx-json:2.3.2")
```

In your Android and iOS source sets, make sure you also use the same Ktor version:

```
// iosMain

implementation("io.ktor:ktor-client-darwin:2.3.2")

// androidMain
implementation("io.ktor:ktor-client-android:2.3.2")
```

Unfortunately, the kx.serialization repo (https://github.com/Kotlin/kotlinx.serialization) still references the 1.8.21 artifacts, which is confusing when you're copy-pasting together the different versions. It would be nice if this incompatibility would be shown as a warning/error at build time, rather than throw a runtime error.

Try making these changes to your project. It works for me locally, so I'm hopeful.

**Comment by hodakl099** [comment]
Thank you for your time, indeed it works.

**Comment by SebastianAigner** [comment]
Awesome to hear. We're also going to be pinning a comment under the video to hopefully help others who are in the same situation.

**Comment by H-AbdulMateen** [comment]
Thanks, it worked.
